services:
  - type: web
    name: mpin-analyzer
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python simple_run.py
    healthCheckPath: /health
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
